#
# Load the device configuration for Mitsubishi CN105 Controller.  This is a direct
# replacement for Mitsubishi Kumo Cloud Wifi Controller (Model PAC-USWHS002-WF-1)
#
packages:
  - github://jeffgregx2/ESPHomeCN105/home_assistant/common/mitsubishi_cn105_config.yaml@main
  - github://jeffgregx2/ESPHomeCN105/home_assistant/common/mitsubishi_cn105_wifi_dynamic.yaml@main
  - github://jeffgregx2/ESPHomeCN105/home_assistant/common/mitsubishi_cn105_no_remote_temp.yaml@main
  - github://jeffgregx2/ESPHomeCN105/home_assistant/common/mitsubishi_cn105_device_base.yaml@main

# The packages have requirements regarding substitutions that need to be answered.
substitutions:
  name: midu-climate-guest-bedroom
  friendly_name: Mitsubishi Guest Bedroom
  
  # Wifi Setup - static configuration
  wifi_ssid: !secret wifi_iot_ssid
  wifi_password: !secret wifi_iot_password

  # Wifi Access Point Fallback
  wifi_ap_fallback_ssid: !secret fallback_ssid_midu_guest_bedroom
  wifi_ap_fallback_password: !secret fallback_password_midu_guest_bedroom

  # Various passwords
  api_key: !secret api_key_midu_guest_bedroom
  ota_key: !secret ota_key_midu_guest_bedroom

  # Setup web server authentication
  # To disable the web server add the following after the substitution section:
  #     web_server: !remove
  ws_username: !secret web_server_username
  ws_password: !secret web_server_password

# Disable the web server component
web_server: !remove

